eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring:
  application:
    name: api-gateway

    cloud:
      gateway:
        routes:
          ## Booking Service ROUTE
          - id: booking-service
            uri: lb://booking-service
            predicates:
              - Path=/api/booking
          ## Catalog Service ROUTE
          - id: catalog-service
            uri: lb://catalog-service
            predicates:
              - Path=/api/catalog
          ## Feedback Service ROUTE
          - id: feedback-service
            uri: lb://feedback-service
            predicates:
              - Path=/api/feedback
          ## Schedule Service ROUTE
          - id: schedule-service
            uri: lb://schedule-service
            predicates:
              - Path=/api/schedule
          ## User Service ROUTE
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/user
          ## Discovery Server ROUTE
          - id: discovery-server
            uri: http://localhost:8761/eureka
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          ## Discovery Server Static Resources ROUTE
          - id: discovery-server-static
            uri: http://localhost:8761/eureka
            predicates:
              - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-barber-shop-realm